# docker-compose.prod.yml
# Production configuration untuk deployment
version: '3.8'

services:
  brin-client-count:
    image: nojinnojs/brin-client-count:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.brin-client-count.rule=Host(`brin-client-count.local`)"
      - "traefik.http.services.brin-client-count.loadbalancer.server.port=3000"
