# docker-compose.yml
version: '3.8'

services:
  # Development service (local build)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - dev

  # Production service (local build)
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - prod

  # Production service (Docker Hub image)
  app-hub:
    image: nojinnojs/brin-client-count:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - hub

  # Development service (Docker Hub image)
  app-hub-dev:
    image: nojinnojs/brin-client-count:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - hub-dev
